name: Build and Deploy

on: 
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        container: node:slim
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              name: use nodejs
              with:
                node-version: "latest"
                check-latest: true
            - run: npm i

            - uses: appleboy/ssh-action@master
              name: Deploy package to idcloudhost
              with:
                host: ${{secrets.HOST}}
                port: ${{secrets.PORT}}
                username: ${{secrets.USERNAME}}
                key: ${{secrets.PRIVATE_KEY}}
                script: |
                   git pull origin main
                   git status
                   npm install
                   npm run dev