name: Up to netlify

on: 
    push:
        branches: ["main"]

    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x,16.x,18.x,20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: pnpm install
      - run: pnpm run build
      - name: Publish to netlify
        uses: South-Paw/action-netlify-cli@1.0.1
        id: netlify
        with:
          args: 'deploy --json --dir \"./dist\" --message \"draft [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      