name: Build and Deploy

on: 
    push:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"

jobs:
    build:
        runs-on: ubuntu-latest
        container: node:slim
        steps:
            - uses: actions/checkout@v3
            - uses: elgohr/Publish-Docker-Github-Action@v5
              name: build and publish to github packages registry
              with:
                name: Jocerdikiawann/Astrolio/astrolio
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                dockerfile: Dockerfile
                tags: v1

            - uses: appleboy/ssh-action@master
              name: Deploy package to idcloudhost
              env: 
                GITHUB_USERNAME: ${{github.actor}}
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                host: ${{secrets.HOST}}
                port: ${{secrets.PORT}}
                username: ${{secrets.USERNAME}}
                key: ${{secrets.PRIVATE_KEY}}
                envs: GITHUB_USERNAME, GITHUB_TOKEN
                script: |
                    docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
                    docker pull ghcr.io/Jocerdikiawann/Astrolio/astrolio:v1
                    docker stop astrolio
                    docker system prune -f
                    docker run astrolio -p 3000:3000 ghcr.io/Jocerdikiawann/Astrolio/astrolio:v1